[build]
  publish = "."
  functions = "netlify/functions"

# (opzionale) forza SW a essere servito dalla root
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Service-Worker-Allowed = "/"
